name: Publish to Confluence
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: markdown-confluence
        uses: markdown-confluence/publish-action@v5
            
        with:
          confluenceBaseUrl: https://wexinc.atlassian.net/wiki/spaces/~712020f93207a80b2f4d3e88e86eaf0d4ef6d2
          confluenceParentId: 154382991740
          atlassianUserName: ${{ secrets.ATLASSIAN_USERNAME }}
          atlassianApiToken: ${{ secrets.ATLASSIAN_API_TOKEN }}
