
name: Publish to Confluence
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: markdown-confluence
        uses: markdown-confluence/publish-action@v5
            
        with:
          confluenceBaseUrl: https://wexinc.atlassian.net/
          confluenceParentId: 154384302313
          atlassianUserName: ${{ secrets.ATLASSIAN_USERNAME }}
          atlassianApiToken: ${{ secrets.ATLASSIAN_API_TOKEN }}
          folderToPublish: text
